# Generated by Django 2.1 on 2018-08-16 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='starter',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
