# Generated by Django 2.1 on 2018-08-16 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20180816_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete='cascade', related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
